### ISSUE TITLE
Cannot run when installed in a virtualenv due to mainwindow/appmenu.xml not found

### ISSUE THREAD

**Issue by muelli** [openpaperwork/paperwork#628]
I tried to give paperwork a try and I installed it in a virtualenv (as opposed to install it system wide or straight from the repository):

```
➜ paperwork>virtualenv --system-site-packages --python=python3 /tmp/ppw3
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/ppw3/bin/python3
Also creating executable in /tmp/ppw3/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
➜ paperwork>/tmp/ppw3/bin/pip install paperwork
Collecting paperwork
Collecting pycountry (from paperwork)
Collecting pyocr>=0.3.0 (from paperwork)
Collecting paperwork-backend>=1.1 (from paperwork)
Collecting pyinsane2 (from paperwork)
Collecting termcolor (from paperwork)
Collecting python-Levenshtein (from paperwork)
Collecting pypillowfight (from paperwork)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from paperwork)
Requirement already satisfied: six in /tmp/ppw3/lib/python3.5/site-packages (from pyocr>=0.3.0->paperwork)
Collecting pyenchant (from paperwork-backend>=1.1->paperwork)
Collecting Whoosh (from paperwork-backend>=1.1->paperwork)
  Using cached Whoosh-2.7.4-py2.py3-none-any.whl
Collecting simplebayes (from paperwork-backend>=1.1->paperwork)
  Using cached simplebayes-1.5.8-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /tmp/ppw3/lib/python3.5/site-packages (from python-Levenshtein->paperwork)
Requirement already satisfied: packaging>=16.8 in /tmp/ppw3/lib/python3.5/site-packages (from setuptools->python-Levenshtein->paperwork)
Requirement already satisfied: appdirs>=1.4.0 in /tmp/ppw3/lib/python3.5/site-packages (from setuptools->python-Levenshtein->paperwork)
Requirement already satisfied: pyparsing in /tmp/ppw3/lib/python3.5/site-packages (from packaging>=16.8->setuptools->python-Levenshtein->paperwork)
Installing collected packages: pycountry, pyocr, pyenchant, Whoosh, termcolor, python-Levenshtein, simplebayes, paperwork-backend, pyinsane2, pypillowfight, paperwork
Successfully installed Whoosh-2.7.4 paperwork-1.1.1 paperwork-backend-1.1.2 pycountry-17.1.8 pyenchant-1.6.8 pyinsane2-2.0.9 pyocr-0.4.6 pypillowfight-0.2.1 python-Levenshtein-0.12.0 simplebayes-1.5.8 termcolor-1.1.0
➜ paperwork>/tmp/ppw3/bin/paperwork
WARNING paperwork.paperwork            No suitable localization file found.
INFO   pyinsane2.sane.abstract_proc   Starting Pyinsane subprocess
INFO   pyinsane2.sane.abstract_proc   Pyinsane pipes: /tmp/pyinsane_pk29fyv3/pipe_c2s | /tmp/pyinsane_pk29fyv3/pipe_s2c
INFO   pyinsane2.sane.abstract_proc   Connected to Pyinsane subprocess
INFO   paperwork_backend.config       Config file not found. Will use '/home/muelli/.config/paperwork.conf'
INFO   paperwork_backend.config       Reloading /home/muelli/.config/paperwork.conf ...
/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py:2779: Warning: g_set_application_name() called multiple times
  GLib.set_application_name(_("Paperwork"))
ERROR  paperwork.frontend.util        Can't find resource file 'mainwindow/appmenu.xml'. Aborting
INFO   paperwork.paperwork            Good bye
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/tmp/ppw3/bin/paperwork", line 6, in <module>
    main()
  File "/tmp/ppw3/lib/python3.5/site-packages/paperwork/paperwork.py", line 144, in main
    main_win = MainWindow(config)
  File "/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2297, in __init__
    self.__advanced_app_menu = self.__init_app_menu(config, self.app)
  File "/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2826, in __init_app_menu
    app_menu = load_uifile(os.path.join("mainwindow", "appmenu.xml"))
  File "/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/util/__init__.py", line 144, in load_uifile
    raise Exception("Can't find resource file '%s'. Aborting" % filename)
Exception: Can't find resource file 'mainwindow/appmenu.xml'. Aborting
ERROR  paperwork.frontend.diag        ===========================
➜ paperwork>find /tmp/ppw3 -name 'appmenu.xml'
/tmp/ppw3/lib/python3.5/site-packages/tmp/paperwork3/share/paperwork/mainwindow/appmenu.xml
➜ paperwork>strace -f -eopen /tmp/ppw3/bin/paperwork 2>&1 | grep mainwind
open("/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__pycache__/__init__.cpython-35.pyc", O_RDONLY|O_CLOEXEC) = 7
open("/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 7
open("/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__pycache__/docs.cpython-35.pyc", O_RDONLY|O_CLOEXEC) = 7
open("/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__pycache__/pages.cpython-35.pyc", O_RDONLY|O_CLOEXEC) = 7
open("/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__pycache__/scan.cpython-35.pyc", O_RDONLY|O_CLOEXEC) = 7
[pid 24238] open("/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", O_RDONLY|O_CLOEXEC) = 10
/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py:2779: Warning: g_set_application_name() called multiple times
ERROR  paperwork.frontend.util        Can't find resource file 'mainwindow/appmenu.xml'. Aborting
  File "/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2297, in __init__
  File "/tmp/ppw3/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2826, in __init_app_menu
    app_menu = load_uifile(os.path.join("mainwindow", "appmenu.xml"))
Exception: Can't find resource file 'mainwindow/appmenu.xml'. Aborting
➜ paperwork>

```

I would expect that installing in "site-packages/tmp/" is a bug.

**Comment by jflesch** [comment]
Can you try with the [unstable branches of paperwork-backend and paperwork](https://github.com/openpaperwork/paperwork/blob/unstable/doc/install.devel.markdown) please?
It should already be fixed.

**Comment by muelli** [comment]
nah. I don't want to install system-wide nor necessarily a development version.  I expected to be able to install and run paperwork just as any other application available via PyPI.
Feel free to close if you don't think it's a bug.  I would expect paperwork to be the only project installing its resources in `site-packages/tmp` though.

**Comment by jflesch** [comment]
It should be fixed when unstable (future 1.2.x) will become stable (in other words, when 1.2 will be released).

**Comment by muelli** [comment]
yay!

Although I've tried `pip install -U 'git+https://github.com/openpaperwork/paperwork/#egg=paperwork` (and the backend), but it still fails with the same error. I guess I try again when the new version has been pushed to pypi.

**Comment by muelli** [comment]
I withdraw my previous comment. I was in the wrong virtualenv. The application is starting now. yay :)
